### ISSUE TITLE
fs.existsSync is not a function

### ISSUE THREAD

**Issue by voxpopgames** [nklayman/vue-cli-plugin-electron-builder#1068]
**Describe the bug**
Hello I am new to electron and due as well, after updating vue-cli-plugin-electron-builder to 2.0.0-rc.4 to make windows exe builds, I am unable to run my application In development mode

**To Reproduce**
Upon pressing yarn serve to run the application in development mode I receive the error:

![Screen Shot 2020-10-06 at 5 29 12 PM](https://user-images.githubusercontent.com/66039711/95262162-9c920b00-07f9-11eb-8590-1887d5f3f14d.png)

I have tried the solutions under #484 and #896, but still no success. I am not even sure where the problem begins.

**Environment (please complete the following information):**
System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  undefined (1.1.2)
    @vue/babel-preset-app:  3.12.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  undefined (1.1.2)
    @vue/babel-sugar-inject-h:  undefined (1.1.2)
    @vue/babel-sugar-v-model:  undefined (1.1.2)
    @vue/babel-sugar-v-on:  undefined (1.1.2)
    @vue/cli-overlay:  4.5.6 
    @vue/cli-plugin-babel: ^3.4.1 => 3.12.1 
    @vue/cli-plugin-e2e-cypress: ^3.4.1 => 3.12.1 
    @vue/cli-plugin-eslint: ^4.5.4 => 4.5.6 
    @vue/cli-plugin-pwa: ^3.4.1 => 3.12.1 
    @vue/cli-plugin-router:  4.5.6 
    @vue/cli-plugin-vuex:  4.5.6 
    @vue/cli-service: ^4.5.4 => 4.5.6 
    @vue/cli-shared-utils:  3.12.1 (4.5.6)
    @vue/component-compiler-utils:  3.2.0 
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.1 
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.2.0 
    @websanova/vue-auth: ^2.21.14-beta => 2.21.14-beta 
    bootstrap-vue: ^2.16.0 => 2.17.3 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 
    portal-vue:  2.1.7 
    vue: ^2.6.6 => 2.6.12 
    vue-axios: ^2.1.4 => 2.1.5 
    vue-carousel: ^0.18.0-alpha => 0.18.0 
    vue-cli-plugin-electron-builder: ^2.0.0-rc.4 => 2.0.0-rc.4 
    vue-eslint-parser:  5.0.0 
    vue-functional-data-merge:  3.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-i18n: ^8.21.0 => 8.21.1 
    vue-loader:  15.9.3 (16.0.0-beta.8)
    vue-progress-path: ^0.0.2 => 0.0.2 
    vue-router: ^3.4.3 => 3.4.5 
    vue-sidebar-menu: ^3.6.2 => 3.12.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.5.1 => 3.5.1 
    vuex-electron: ^1.0.3 => 1.0.3 
    vuex-rest-api: ^2.13.0 => 2.13.0 
  npmGlobalPackages:
    @vue/cli: 4.1.2

**Comment by nklayman** [comment]
As of version 2.0.0 of this plugin, `nodeIntegration` is disabled by default to improve security and match electron's default behavior. If your app uses native modules in the renderer process (which it appears to do based on the error), you will have to [enable nodeIntegration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) in your app. Hopefully this fixes your issue.

**Comment by voxpopgames** [comment]
Thank you for responding! The nodeIntegration suggestion was definitely helpful, however it put me amongst another problem of: 
![Screen Shot 2020-10-07 at 10 26 07 AM](https://user-images.githubusercontent.com/66039711/95344340-8af74480-0887-11eb-821e-4cf60df2a016.png)

It seems that electron is being deemed undefined for some reason. I did check your response in #703 and went about your steps, but the problem still persists. Would you happen to have anymore suggestions as to how I can resolve this?

Thank you for your time.

**Comment by voxpopgames** [comment]
https://github.com/sindresorhus/electron-store/issues/138 helped solve my issue! Thank you again!
