### ISSUE TITLE
Electron 5.0.0 error during load

### ISSUE THREAD

**Issue by rohiptmp** [nklayman/vue-cli-plugin-electron-builder#250]
**Describe the bug**
After updating Electron to 5.0.0, starting an app with npm run electron:serve failes with:

```
App threw an error during load
TypeError: electron__WEBPACK_IMPORTED_MODULE_0__.protocol.registerStandardSchemes is not a function
    at eval (webpack:///./src/background.js?:16:51)
    at Module../src/background.js (/Users/vs360/Temp/vue-test/dist_electron/index.js:1201:1)
    at __webpack_require__ (/Users/vs360/Temp/vue-test/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (/Users/vs360/Temp/vue-test/dist_electron/index.js:1212:1)
    at __webpack_require__ (/Users/vs360/Temp/vue-test/dist_electron/index.js:20:30)
    at /Users/vs360/Temp/vue-test/dist_electron/index.js:84:18
    at Object.<anonymous> (/Users/vs360/Temp/vue-test/dist_electron/index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
```

**To Reproduce**
`vue create vue-test`
`cd vue-test/`
`vue add electron-builder`

update electron to 5.0.0

`npm run electron:serve`

**Environment (please complete the following information):**
```
{
  "name": "vue-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "vue": "^2.6.10"
  },
  "devDependencies": {
    "@vue/cli-service": "^3.6.0",
    "electron": "^5.0.0",
    "vue-cli-plugin-electron-builder": "^1.2.0",
    "vue-template-compiler": "^2.5.21"
  }
}
```

**Comment by crossle** [comment]
See the break change https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#privileged-schemes-registration

**Comment by nklayman** [comment]
Upgrade to `v1.3.0`, delete your `background.js`, and reinvoke the generator by running `vue invoke electron-builder`.

**Comment by CristianH033** [comment]
I deleted the `background.js `file and ran the command `vue invoke electron-builder`, it didn't work, no new file was created.

**Comment by nklayman** [comment]
Make sure the plugin version is `1.3.0`.
