### ISSUE TITLE
Can’t use ipcRenderer in 2.0.0-beta.4

### ISSUE THREAD

**Issue by getflourish** [nklayman/vue-cli-plugin-electron-builder#671]
**Describe the bug**
I can’t use `ipcRenderer` in the beta. It works fine in the latest stable 1.45 release.

**To Reproduce**

1. Install a fresh Vue CLI project (latest version)
2. Installed 2.0.0-beta.4
3. In `main.js`, import or require `ipcRenderer`

```
const {
  ipcRenderer
} = require("electron")
```
Error in the launched Electron webview:
```
index.js?bdb9:7 Uncaught TypeError: fs.existsSync is not a function
    at getElectronPath (index.js?bdb9:7)
    at eval (index.js?bdb9:18)
    at Object../node_modules/electron/index.js (chunk-vendors.js:1058)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (main.js?56d7:15)
    at Module../src/main.js (app.js:1153)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at Object.1 (app.js:1226)
```

Looks like a  problem with require or `nodeIntegration`? 

**Environment (please complete the following information):**
- OS and version: macOS 10.13
- Electron 7.0.0
- Spectron 9.0.0
- node version: 10.13
- vue-cli-plugin-electron-builder version : 2.0.0-beta.4

**Comment by getflourish** [comment]
Okay, reading the release docs, I figured it out.

module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true
    }
  }
}
