### ISSUE TITLE
fs.existsSync is not a function

### ISSUE THREAD

**Issue by eric112** [nklayman/vue-cli-plugin-electron-builder#896]
when I update the plugin from 1.4.6 to 2.0, there was an error when I ran the project:`fs.existsSync is not a function`.How can I fix it？
```
Uncaught TypeError: fs.existsSync is not a function
    at getElectronPath (webpack-internal:///./node_modules/electron/index.js:7)
    at eval (webpack-internal:///./node_modules/electron/index.js:18)
    at Object../node_modules/electron/index.js (chunk-vendors.js:4359)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/GlobalBar.vue?vue&type=script&lang=js&:24)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/GlobalBar.vue?vue&type=script&lang=js& (app.js:1030)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (webpack-internal:///./src/components/GlobalBar.vue?vue&type=script&lang=js&:2)
```

**Comment by eric112** [comment]
I've found a solution in https://github.com/electron/electron/issues/9920#issuecomment-478826728

**Comment by CodeDiseaseDev** [comment]
....... how about a normal node js app?
